include: "rules/common.smk"
include: "rules/setup.smk"
include: "rules/mapping.smk"
include: "rules/stats.smk"


rule all:
    input:
        "reports/multiqc/samtools/flagstat/report.html"
        #"reports/multiqc/mosdepth/report.html",
        #"reports/multiqc/markduplicates/report.html"
        #expand(bam_folder_path("{sample}.rmdup.bam.bai"), sample=samples.index[0]),
