include: "rules/common.smk"
include: "rules/setup.smk"
include: "rules/mapping.smk"
include: "rules/stats.smk"


rule all:
    input:
        expand("reports/multiqc/samtools/flagstat{raw_or_rmdup}/report.html", raw_or_rmdup=['raw','rmdup'])
        #"reports/multiqc/mosdepth/report.html",
        #"reports/multiqc/markduplicates/report.html"
        #expand(bam_folder_path("{sample}.rmdup.bam.bai"), sample=samples.index[0]),
